### ISSUE TITLE
Can you please implement from incidence matrix to adjacency lists as well?

### ISSUE THREAD

**Issue by FarzanKh** [alphamuth/Conversion-of-Graph-representation-in-Graph-Theory#1]

**Comment by imrrahul** [comment]
It's implemented there:

https://github.com/imrrahul/Conversion-of-Graph-representation-in-Graph-Theory/blob/5b71b5ebc1d510ae6b1f51421f25c762b569b2f0/graph_convert.py#L78

**Comment by FarzanKh** [comment]
Thank you

**Comment by FarzanKh** [comment]
Can I ask you a favor? Are you available for 15 minutes that I can set up a video call with you and ask you some questions about this code? I promise it won't take more than 15 min
